== 图论简介

=== 基础

==== 有向图和无向图

用图可以对事物以及事物之间的联系建模。首先来弄清楚下图中的有向图和无向图的不同。在一个有向图中，联系是从源顶点到目标顶点。万维网中的一个页面到另一个页面的链接，学术论文中的引用，都是比较典型的例子。在有向图中，一条边的两个顶点一般扮演着不同的角色，如父子关系，页面A链接向页面B。

在一个无向图中，边没有方向：关系都是对称的。社交网络中一个典型的联系是，通常A如果是B的朋友，我们很可能认为B也是A的朋友。更进一步，如果我们到Kevin Bacon是六度关系，那么Kevin Bacon到我们也是六度关系 。

GraphX中的一个重要概念是，所有的边都有一个方向，那么图就是有向图；如果忽略边的方向，就是无向图。

==== 有环图和无环图

有环图是包含循环的，一系列顶点连接成一个环(参见下图)。一个无环图没有环。需要了解有环图和无环图的区别的原因是，如果你有一个算法，通过连接的顶点，沿着连接的边 ， 有向图就会造成这样的风险：恰当的算法实现会卡住，在环上永远循环下去。

有环图的一个有趣的特征是，其形成一个三角形关系，即每个顶点都与其他两个顶点相连。三角形关系的用途之一是作为一个预测特征来区分垃圾邮件和非垃圾邮件。

==== 有标签的图和无标签的图

有标签的图是顶点或边除了有唯一标示，还有与之关联的数据(标签)(参见下图)。对顶点做了标签的称为顶点标签图，对边做了标签的称为边标签图。

GraphX用GraphLoader.edgeListFile()创建边，它同时会对边的两个顶点(源顶点和目标顶点)创建一个默认属性值1。

一个确定了边标签类型的图也就是大家熟知的权重图。权重图一般会用作计算比如城镇之间的最短路径。这里提到的权重是对边打标签，表示两个顶点(城镇)间的距离。

==== 平行边和环

平行边和环的区别在于，是否允许在同一对顶点上同时存在多条边，还是边的起点和终点都是同一个顶点，如下图所示的两种可能性。GrapbX是伪图，会存在平行边和自环，所以需要通过 groupEdges()和subgraph()来排除这两种情况。

==== 二分图

二分图有一个如下图所示的特定的结构，整个图的顶点被分成两个不同的集合，所有的源顶点是一个集合(所有源顶点之间没有联系)，所有的目标顶点是一个集合(目标顶点之间没有联系)，在两个集合内都不存在相连的边。

可以用二分图对两个不同类型实体之间的关系建模。例如，对于申请上大学的学生，把每个学生划分到一个顶点集合，把要申请的大学划分为另一个顶点集合。

另一个例子是推荐系统，把用户划分在一个集合中，用户所购买的产品划分在另一个集合中。

=== RDF图和属性图

资源描述框架(RDF)是由万维网联盟(W3C)在1997年首次提出的针对语义阶b的图标准。它实现了一部分2004年开始更新的RDFa标准。旧的图数据库/图处理系统只支持RDF三元组(主体、谓词、对象)，而新的图数据库/图处理系统(包括GraphX)支持属性图(参见下图)。

由于其自身的局限性，RDF三元组必须扩展到四元组(包括某种身份)甚至五元组(包括一些所谓的上下文)。这些都是RDF图的问题。但尽管其有局限性，RDF图由于图数据的原因还是很重要的，例如来自维基百科、WordNet和地理名称的YAG02数据库。

属性图很容易满足新的图数据的需要。

=== 邻接矩阵

另一种表示图论的方式是邻接矩阵(参见下图)，这不是GraphX表示图的方式。抛开GraphX，Spark的MLlib机器学习库已经支持邻接矩阵，还有更通用的稀疏矩阵。如果你不需要边属性，可以在MLlib找到比GraphX性能更好的算法。例如，推荐系统，从性能的角度来看，mllib.recommendation.ALS会是比graphx.lib.SVDPlusPlus更好的选择，虽然不同场景适用不同算法。SVDPlusPlus会在后面具体介绍。
